import { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
  await knex('events').insert([
    {
      event_code: 'EVT-001',
      name: 'Global Tech Summit 2024',
      type: 'Conference',
      start_date: new Date('2024-01-15'),
      end_date: new Date('2024-01-17'),
      owner: 'Sarah Jenkins',
      location: 'London, UK',
      total_registrations: 1250,
      checked_in_count: 980,
      capacity: 1500,
      status: 'Published',
      is_registration_open: true,
      is_checkin_active: false,
    },
    {
      event_code: 'EVT-002',
      name: 'Product Innovation Workshop',
      type: 'Workshop',
      start_date: new Date('2024-02-10'),
      end_date: new Date('2024-02-11'),
      owner: 'Michael Chen',
      location: 'San Francisco, CA',
      total_registrations: 320,
      checked_in_count: 0,
      capacity: 400,
      status: 'Published',
      is_registration_open: true,
      is_checkin_active: false,
    },
    {
      event_code: 'EVT-003',
      name: 'Design Excellence Awards',
      type: 'Awards',
      start_date: new Date('2024-03-20'),
      end_date: new Date('2024-03-20'),
      owner: 'Emily Rodriguez',
      location: 'New York, NY',
      total_registrations: 850,
      checked_in_count: 0,
      capacity: 1000,
      status: 'Published',
      is_registration_open: true,
      is_checkin_active: false,
    },
    {
      event_code: 'EVT-004',
      name: 'Startup Pitch Competition',
      type: 'Conference',
      start_date: new Date('2024-04-05'),
      end_date: new Date('2024-04-06'),
      owner: 'James Wilson',
      location: 'Austin, TX',
      total_registrations: 0,
      checked_in_count: 0,
      capacity: 500,
      status: 'Draft',
      is_registration_open: false,
      is_checkin_active: false,
    },
    {
      event_code: 'EVT-005',
      name: 'Annual Community Meetup',
      type: 'Meetup',
      start_date: new Date('2024-03-05'),
      end_date: new Date('2024-03-05'),
      owner: 'Lisa Thompson',
      location: 'Seattle, WA',
      total_registrations: 180,
      checked_in_count: 0,
      capacity: 200,
      status: 'Published',
      is_registration_open: true,
      is_checkin_active: false,
    },
    {
      event_code: 'EVT-006',
      name: 'Executive Leadership Summit',
      type: 'Conference',
      start_date: new Date('2024-04-12'),
      end_date: new Date('2024-04-14'),
      owner: 'David Park',
      location: 'Chicago, IL',
      total_registrations: 650,
      checked_in_count: 0,
      capacity: 800,
      status: 'Published',
      is_registration_open: true,
      is_checkin_active: false,
    },
    {
      event_code: 'EVT-007',
      name: 'Design Thinking Workshop',
      type: 'Workshop',
      start_date: new Date('2024-01-08'),
      end_date: new Date('2024-01-09'),
      owner: 'Nina Patel',
      location: 'Boston, MA',
      total_registrations: 95,
      checked_in_count: 82,
      capacity: 100,
      status: 'Completed',
      is_registration_open: false,
      is_checkin_active: false,
    },
  ]);
}

export async function down(knex: Knex): Promise<void> {
  await knex('events').del();
}
